### ISSUE TITLE
Issue with font

### ISSUE THREAD

**Issue by ItsEternity** [Aiden3043/Minimalistcord#1]
Hey, I downloaded the Minimalistcord theme but when I use it on Discord the font goes all funny.

http://prntscr.com/az33a2

Do you guys know how to fix this? Using the latest version of BetterDiscord and Discord

**Comment by ConnerFrancis** [comment]
You need to install the Roboto fonts onto your computer. I recommend downloading bold, italic, and normal. That should solve the problem. If it doesnt, let me know!
